import type { CandidateStop } from "@/lib/highways/highway-relevance";

export type HighwayStop = CandidateStop & {
  lat: number;
  lng: number;
  highway: string;
  locality: string;
  priceLabel: "Free" | "Customer access" | "Unknown";
  facilities: string[];
  placeId?: string;
};

export const sampleHighwayStops: HighwayStop[] = [
  {
    id: "shree-datta-snacks-mumbai-pune",
    name: "Shree Datta Snacks",
    category: "restaurant_proxy",
    distanceFromRouteMeters: 240,
    distanceFromHighwayMeters: 120,
    detourMinutes: 4,
    isEndpointStagingArea: false,
    isInsideDenseCity: false,
    source: "crowdsourced",
    confidence: 0.82,
    openNow: true,
    verified: true,
    lat: 18.764,
    lng: 73.376,
    highway: "Mumbai-Pune Expressway",
    locality: "Khalapur-Lonavala service corridor",
    priceLabel: "Customer access",
    facilities: ["Vegetarian", "Parking", "Separate washrooms"],
  },
  {
    id: "7-midway-plaza-hyderabad-vijayawada",
    name: "7 Midway Plaza",
    category: "food_plaza",
    distanceFromRouteMeters: 160,
    distanceFromHighwayMeters: 60,
    detourMinutes: 4,
    isEndpointStagingArea: false,
    isInsideDenseCity: false,
    source: "crowdsourced",
    confidence: 0.9,
    openNow: true,
    verified: true,
    lat: 17.143,
    lng: 79.624,
    highway: "NH-65",
    locality: "Hyderabad-Vijayawada Suryapet corridor",
    priceLabel: "Customer access",
    facilities: ["Food court", "Parking", "Lighting"],
  },
  {
    id: "raju-gari-thota-hyderabad-vijayawada",
    name: "Raju Gari Thota",
    category: "food_plaza",
    distanceFromRouteMeters: 220,
    distanceFromHighwayMeters: 90,
    detourMinutes: 5,
    isEndpointStagingArea: false,
    isInsideDenseCity: false,
    source: "crowdsourced",
    confidence: 0.86,
    openNow: true,
    verified: true,
    lat: 16.506,
    lng: 80.648,
    highway: "NH-65",
    locality: "Hyderabad-Vijayawada Vijayawada corridor",
    priceLabel: "Customer access",
    facilities: ["Family restaurant", "Separate washrooms", "Parking"],
  },
  {
    id: "lavato-nh44-krishnagiri",
    name: "Lavato",
    category: "public_restroom",
    distanceFromRouteMeters: 120,
    distanceFromHighwayMeters: 40,
    detourMinutes: 3,
    isEndpointStagingArea: false,
    isInsideDenseCity: false,
    source: "crowdsourced",
    confidence: 0.95,
    openNow: true,
    verified: true,
    lat: 12.518,
    lng: 78.214,
    highway: "NH-44",
    locality: "Krishnagiri toll plaza",
    priceLabel: "Customer access",
    facilities: ["Premium lavatory", "Attendant", "Parking"],
  },
  {
    id: "hotel-highway-king-nh48",
    name: "Hotel Highway King",
    category: "restaurant_proxy",
    distanceFromRouteMeters: 260,
    distanceFromHighwayMeters: 120,
    detourMinutes: 5,
    isEndpointStagingArea: false,
    isInsideDenseCity: false,
    source: "crowdsourced",
    confidence: 0.86,
    openNow: true,
    verified: true,
    lat: 27.988,
    lng: 76.382,
    highway: "NH-48",
    locality: "Delhi-Jaipur Neemrana Shahpura corridor",
    priceLabel: "Customer access",
    facilities: ["Family restaurant", "Parking", "Separate washrooms"],
  },
];
