import type { CuratedStopCandidate, HighwaySearchCorridor, HygieneProxyBrand } from "./highway-place-discovery";

export const proxyBrands: HygieneProxyBrand[] = [
  { brandName: "McDonald's", region: "Pan-India", proxyType: "qsr", defaultConfidence: 0.78, notes: "International QSR baseline for reliable sanitation on highway food courts" },
  { brandName: "Burger King", region: "Pan-India", proxyType: "qsr", defaultConfidence: 0.76, notes: "QSR proxy when attached to highway plazas or premium fuel stations" },
  { brandName: "KFC", region: "Pan-India", proxyType: "qsr", defaultConfidence: 0.74, notes: "QSR proxy for organized food courts" },
  { brandName: "Pizza Hut", region: "Pan-India", proxyType: "qsr", defaultConfidence: 0.72, notes: "QSR proxy for organized family stops" },
  { brandName: "Costa Coffee", region: "Pan-India", proxyType: "qsr", defaultConfidence: 0.72, notes: "Cafe proxy inside premium wayside amenities" },
  { brandName: "Cube Stop", region: "Pan-India", proxyType: "wayside_amenity", defaultConfidence: 0.9, notes: "Cube Highways amenity with dedicated Wash Stop" },
  { brandName: "PATH Recharge", region: "Pan-India", proxyType: "wayside_amenity", defaultConfidence: 0.88, notes: "Mall-like wayside amenities with EV charging" },
  { brandName: "Village Food Courts", region: "Pan-India", proxyType: "food_plaza", defaultConfidence: 0.86, notes: "Large food court highway amenity proxy" },
  { brandName: "Shell Select", region: "Pan-India", proxyType: "fuel_cafe", defaultConfidence: 0.78, notes: "Frequent road-tripper proxy for clean fuel station restrooms" },
  { brandName: "Shell Cafe", region: "Pan-India", proxyType: "fuel_cafe", defaultConfidence: 0.76, notes: "Cafe-attached fuel stop restroom proxy" },
  { brandName: "Jio-bp", region: "Pan-India", proxyType: "fuel_cafe", defaultConfidence: 0.82, notes: "Modern mobility station with sanitized washrooms" },
  { brandName: "Wild Bean Cafe", region: "Pan-India", proxyType: "fuel_cafe", defaultConfidence: 0.8, notes: "Cafe inside Jio-bp mobility station" },
  { brandName: "Indian Oil Swagat", region: "Pan-India", proxyType: "wayside_amenity", defaultConfidence: 0.78, notes: "Flagship wayside amenities at COCO pumps" },
  { brandName: "Indian Oil COCO", region: "Pan-India", proxyType: "fuel_station", defaultConfidence: 0.74, notes: "Company-operated fuel station proxy" },
  { brandName: "BPCL Ghar", region: "Pan-India", proxyType: "wayside_amenity", defaultConfidence: 0.78, notes: "One Stop Trucker Shop with branded rest-stop facilities" },
  { brandName: "Reliance", region: "Pan-India", proxyType: "fuel_station", defaultConfidence: 0.78, notes: "Standalone fuel operator often rated highly for washrooms" },
  { brandName: "Nayara Energy", region: "Pan-India", proxyType: "fuel_station", defaultConfidence: 0.78, notes: "Standalone fuel operator often rated highly for washrooms" },
  { brandName: "Lavato", region: "Pan-India", proxyType: "premium_lavatory", defaultConfidence: 0.95, notes: "Premium AC lavatory service" },
  { brandName: "Hotel Highway King", region: "North & West India", proxyType: "restaurant_proxy", defaultConfidence: 0.88, notes: "Sprawling family highway restaurants on Rajasthan corridors" },
  { brandName: "Honest Restaurant", region: "North & West India", proxyType: "restaurant_proxy", defaultConfidence: 0.82, notes: "Organized Gujarat highway chain" },
  { brandName: "Gallops Food Plaza", region: "North & West India", proxyType: "food_plaza", defaultConfidence: 0.86, notes: "Large Gujarat food plaza and restroom proxy" },
  { brandName: "SN Highway Food Mall", region: "North & West India", proxyType: "food_plaza", defaultConfidence: 0.86, notes: "Rajkot-Ahmedabad food mall proxy" },
  { brandName: "Haldiram's", region: "North & West India", proxyType: "restaurant_proxy", defaultConfidence: 0.82, notes: "Family highway restaurant proxy" },
  { brandName: "Nirula's", region: "North & West India", proxyType: "restaurant_proxy", defaultConfidence: 0.78, notes: "North India route restaurant proxy" },
  { brandName: "Bikanervala", region: "North & West India", proxyType: "restaurant_proxy", defaultConfidence: 0.8, notes: "North India family restaurant proxy" },
  { brandName: "Cheetal Grand", region: "North & West India", proxyType: "restaurant_proxy", defaultConfidence: 0.88, notes: "Known NH-58 family stop" },
  { brandName: "Shree Rathnam", region: "North & West India", proxyType: "restaurant_proxy", defaultConfidence: 0.76, notes: "South Indian vegetarian chain near Delhi/NCR highways" },
  { brandName: "Shree Datta Snacks", region: "North & West India", proxyType: "restaurant_proxy", defaultConfidence: 0.86, notes: "Premium vegetarian highway stop" },
  { brandName: "Vithal Kamats", region: "North & West India", proxyType: "restaurant_proxy", defaultConfidence: 0.84, notes: "Premium vegetarian highway stop" },
  { brandName: "PIK N GO", region: "South India", proxyType: "restaurant_proxy", defaultConfidence: 0.84, notes: "Eco-conscious vegetarian chain marketing sanitized washrooms" },
  { brandName: "7 Midway Plaza", region: "South India", proxyType: "food_plaza", defaultConfidence: 0.9, notes: "Large Hyderabad-Vijayawada food court" },
  { brandName: "Raju Gari Thota", region: "South India", proxyType: "food_plaza", defaultConfidence: 0.88, notes: "Highly rated Hyderabad-Vijayawada highway stop" },
  { brandName: "Adyar Ananda Bhavan", region: "South India", proxyType: "restaurant_proxy", defaultConfidence: 0.84, notes: "A2B organized highway dining model" },
  { brandName: "A2B", region: "South India", proxyType: "restaurant_proxy", defaultConfidence: 0.84, notes: "A2B short-name search target" },
  { brandName: "Savera Group", region: "South India", proxyType: "restaurant_proxy", defaultConfidence: 0.82, notes: "Organized multi-cuisine highway stops" },
  { brandName: "Big Bay India", region: "South India", proxyType: "food_plaza", defaultConfidence: 0.88, notes: "Large NH-44 highway food mall near Bengaluru Airport" },
  { brandName: "Hotel Kamat Lokaruchi", region: "South India", proxyType: "restaurant_proxy", defaultConfidence: 0.86, notes: "Reliable Bengaluru-Mysuru route stop" },
  { brandName: "Nana Hotel", region: "East & Central India", proxyType: "dhaba_proxy", defaultConfidence: 0.78, notes: "NH-16 Odisha dhaba proxy with higher hygiene standards" },
  { brandName: "Behera Dhaba", region: "East & Central India", proxyType: "dhaba_proxy", defaultConfidence: 0.78, notes: "NH-16 Odisha organized dhaba proxy" },
  { brandName: "Azad Hind Dhaba", region: "East & Central India", proxyType: "dhaba_proxy", defaultConfidence: 0.82, notes: "Family-friendly NH-19 chain around Kolkata" },
  { brandName: "National Highway Dhaba", region: "North-East India", proxyType: "dhaba_proxy", defaultConfidence: 0.84, notes: "Trusted Nongpoh stop on Guwahati-Shillong" },
  { brandName: "Raha Highway Dhabas", region: "North-East India", proxyType: "dhaba_proxy", defaultConfidence: 0.78, notes: "Organized Assam highway stops" },
];

export const curatedStopCandidates: CuratedStopCandidate[] = [
  { name: "Lavato", region: "South India", proxyType: "premium_lavatory", highwayContext: "NH-44", routeContext: "Krishnagiri toll plaza", localityHint: "Krishnagiri", defaultConfidence: 0.95, notes: "Premium AC lavatory with controlled access near toll plaza" },
  { name: "Cube Stop Anantapur", region: "South India", proxyType: "wayside_amenity", highwayContext: "NH-44", routeContext: "Bengaluru-Hyderabad", localityHint: "Anantapur", defaultConfidence: 0.9, notes: "Cube Highways Wash Stop location" },
  { name: "Cube Stop Manpur", region: "Central India", proxyType: "wayside_amenity", highwayContext: "NH-3", routeContext: "Agra-Mumbai corridor", localityHint: "Manpur", defaultConfidence: 0.88, notes: "Cube Highways Wash Stop location" },
  { name: "Cube Stop Morena", region: "Central India", proxyType: "wayside_amenity", highwayContext: "NH-3", routeContext: "Agra-Gwalior", localityHint: "Morena", defaultConfidence: 0.88, notes: "Cube Highways Wash Stop location" },
  { name: "PATH Recharge", region: "North India", proxyType: "wayside_amenity", highwayContext: "Eastern Peripheral Expressway", routeContext: "Delhi NCR bypass", localityHint: "Eastern Peripheral Expressway", defaultConfidence: 0.88, notes: "Mall-like wayside amenity with EV charging" },
  { name: "Hotel Highway King Neemrana", region: "North & West India", proxyType: "restaurant_proxy", highwayContext: "NH-48", routeContext: "Delhi-Jaipur", localityHint: "Neemrana", defaultConfidence: 0.88, notes: "Large 24/7 highway restaurant with clean restrooms" },
  { name: "Hotel Highway King Shahpura", region: "North & West India", proxyType: "restaurant_proxy", highwayContext: "NH-48", routeContext: "Delhi-Jaipur", localityHint: "Shahpura", defaultConfidence: 0.86, notes: "Highway King family stop" },
  { name: "Hotel Highway King Bagru", region: "North & West India", proxyType: "restaurant_proxy", highwayContext: "NH-48", routeContext: "Jaipur-Ajmer", localityHint: "Bagru", defaultConfidence: 0.86, notes: "Highway King family stop" },
  { name: "Hotel Highway King Kishangarh", region: "North & West India", proxyType: "restaurant_proxy", highwayContext: "NH-48", routeContext: "Jaipur-Ajmer", localityHint: "Kishangarh", defaultConfidence: 0.86, notes: "Highway King family stop" },
  { name: "Cheetal Grand", region: "North India", proxyType: "restaurant_proxy", highwayContext: "NH-58", routeContext: "Delhi-Haridwar", localityHint: "Khatauli", defaultConfidence: 0.88, notes: "Historic family stop with reliable washrooms" },
  { name: "Gallops Food Plaza", region: "North & West India", proxyType: "food_plaza", highwayContext: "Gujarat highways", routeContext: "Ahmedabad-Rajkot", localityHint: "Gujarat", defaultConfidence: 0.86, notes: "Massive organized highway food plaza" },
  { name: "SN Highway Food Mall", region: "North & West India", proxyType: "food_plaza", highwayContext: "Rajkot-Ahmedabad highway", routeContext: "Rajkot-Ahmedabad", localityHint: "Gujarat", defaultConfidence: 0.86, notes: "Large highway food mall with maintained lavatory blocks" },
  { name: "Hotel Ummiya Annapurna Kathiyawad", region: "North & West India", proxyType: "restaurant_proxy", highwayContext: "NH-8", routeContext: "Anand Gujarat", localityHint: "Anand", defaultConfidence: 0.78, notes: "Organized Kathiyawadi traveler stop" },
  { name: "Sharma Dhaba", region: "North & West India", proxyType: "dhaba_proxy", highwayContext: "NH-11", routeContext: "Jaipur-Sikar", localityHint: "Jaipur Sikar road", defaultConfidence: 0.76, notes: "Family-friendly traditional stop" },
  { name: "Shree Datta Snacks", region: "North & West India", proxyType: "restaurant_proxy", highwayContext: "Mumbai-Pune Expressway", routeContext: "Mumbai-Pune", localityHint: "Khalapur", defaultConfidence: 0.86, notes: "Premium vegetarian stop with separate washrooms" },
  { name: "Vithal Kamats", region: "North & West India", proxyType: "restaurant_proxy", highwayContext: "NH-66", routeContext: "Panvel-Goa", localityHint: "Maharashtra highway", defaultConfidence: 0.84, notes: "Premium vegetarian stop on Konkan route" },
  { name: "7 Midway Plaza", region: "South India", proxyType: "food_plaza", highwayContext: "NH-65", routeContext: "Hyderabad-Vijayawada", localityHint: "Suryapet", defaultConfidence: 0.9, notes: "Large food court praised for clean toilets" },
  { name: "Raju Gari Thota", region: "South India", proxyType: "food_plaza", highwayContext: "NH-65", routeContext: "Hyderabad-Vijayawada", localityHint: "Suryapet corridor", defaultConfidence: 0.88, notes: "Highly rated clean highway stop" },
  { name: "Big Bay India", region: "South India", proxyType: "food_plaza", highwayContext: "NH-44", routeContext: "Bengaluru Airport", localityHint: "Devanahalli", defaultConfidence: 0.88, notes: "Large food mall with hygienic restrooms" },
  { name: "Amaravathi Savera Group", region: "South India", proxyType: "restaurant_proxy", highwayContext: "NH-16", routeContext: "Gudur highway", localityHint: "Gudur", defaultConfidence: 0.82, notes: "Organized multi-cuisine highway stop" },
  { name: "Jai Bhuvaneswari Miltry Hotel", region: "South India", proxyType: "restaurant_proxy", highwayContext: "Bengaluru-Mysuru highway", routeContext: "Bengaluru-Mysuru", localityHint: "Ramanagara", defaultConfidence: 0.78, notes: "Traditional but organized route stop" },
  { name: "Hotel Kamat Lokaruchi", region: "South India", proxyType: "restaurant_proxy", highwayContext: "Bengaluru-Mysuru highway", routeContext: "Bengaluru-Mysuru", localityHint: "Ramanagara", defaultConfidence: 0.86, notes: "Reliable family stop" },
  { name: "Mother's Kitchen", region: "South India", proxyType: "restaurant_proxy", highwayContext: "NH-47", routeContext: "Cochin-Trivandrum", localityHint: "Kerala", defaultConfidence: 0.76, notes: "Clean setup near fuel stations" },
  { name: "Greenhouse", region: "South India", proxyType: "restaurant_proxy", highwayContext: "Mananthavady-Kannur route", routeContext: "Mananthavady-Kannur", localityHint: "Kerala", defaultConfidence: 0.74, notes: "Basic but notably neat toilet facilities" },
  { name: "Nana Hotel", region: "East & Central India", proxyType: "dhaba_proxy", highwayContext: "NH-16", routeContext: "Odisha corridor", localityHint: "Phulnakhara", defaultConfidence: 0.78, notes: "Premium traveler dhaba proxy" },
  { name: "Behera Dhaba", region: "East & Central India", proxyType: "dhaba_proxy", highwayContext: "NH-16", routeContext: "Odisha corridor", localityHint: "Tamando", defaultConfidence: 0.78, notes: "Traditional but maintained traveler stop" },
  { name: "Azad Hind Dhaba", region: "East & Central India", proxyType: "dhaba_proxy", highwayContext: "NH-19", routeContext: "Kolkata-Asansol", localityHint: "West Bengal", defaultConfidence: 0.82, notes: "Organized family dhaba chain" },
  { name: "Sher-e-Punjab Dhaba", region: "East & Central India", proxyType: "dhaba_proxy", highwayContext: "NH-19", routeContext: "Asansol", localityHint: "Asansol", defaultConfidence: 0.78, notes: "Parking and clean washroom traveler note" },
  { name: "City Residency", region: "East & Central India", proxyType: "restaurant_proxy", highwayContext: "NH-19", routeContext: "Asansol", localityHint: "Asansol", defaultConfidence: 0.76, notes: "Traveler-noted parking and clean washrooms" },
  { name: "Khalsa Hotel", region: "East & Central India", proxyType: "dhaba_proxy", highwayContext: "NH-19", routeContext: "Govindpur Jharkhand", localityHint: "Govindpur", defaultConfidence: 0.76, notes: "Well-maintained rest-stop cluster" },
  { name: "Sahu Dhaba", region: "East & Central India", proxyType: "dhaba_proxy", highwayContext: "NH-19", routeContext: "Govindpur Jharkhand", localityHint: "Govindpur", defaultConfidence: 0.74, notes: "Well-maintained rest-stop cluster" },
  { name: "Shahi Darbar", region: "East & Central India", proxyType: "dhaba_proxy", highwayContext: "NH-19", routeContext: "Govindpur Jharkhand", localityHint: "Govindpur", defaultConfidence: 0.74, notes: "Well-maintained rest-stop cluster" },
  { name: "Gargi Surya Vihar", region: "East & Central India", proxyType: "restaurant_proxy", highwayContext: "NH-19", routeContext: "Aurangabad Bihar", localityHint: "Aurangabad Bihar", defaultConfidence: 0.82, notes: "Road-tripper recommended for clean restrooms" },
  { name: "Sardar Ji Family Dhaba", region: "East & Central India", proxyType: "dhaba_proxy", highwayContext: "NH-44", routeContext: "Hyderabad-Nagpur", localityHint: "Hyderabad Nagpur route", defaultConfidence: 0.78, notes: "Separate family sections and well-kept facilities" },
  { name: "National Highway Dhaba", region: "North-East India", proxyType: "dhaba_proxy", highwayContext: "NH-6", routeContext: "Guwahati-Shillong", localityHint: "Nongpoh", defaultConfidence: 0.84, notes: "Trusted Khasi cuisine stop with clean restrooms" },
  { name: "Raha Highway Dhabas", region: "North-East India", proxyType: "dhaba_proxy", highwayContext: "Assam highways", routeContext: "Guwahati-Kaziranga", localityHint: "Raha Assam", defaultConfidence: 0.78, notes: "Organized stop cluster with maintained environments" },
];

export const highwaySearchCorridors: HighwaySearchCorridor[] = [
  corridor("epe-delhi-ncr", "Eastern Peripheral Expressway", "Delhi NCR bypass", "North India", [[28.71, 77.53], [28.58, 77.69], [28.36, 77.55]]),
  corridor("delhi-jaipur-nh48", "NH-48", "Delhi-Jaipur", "North & West India", [[28.39, 76.96], [27.99, 76.39], [27.55, 76.08]]),
  corridor("jaipur-ajmer-nh48", "NH-48", "Jaipur-Ajmer", "North & West India", [[26.84, 75.56], [26.58, 75.17], [26.45, 74.64]]),
  corridor("delhi-haridwar-nh58", "NH-58", "Delhi-Haridwar", "North India", [[29.28, 77.73], [29.47, 77.71], [29.94, 78.16]]),
  corridor("rajkot-ahmedabad", "NH-47", "Rajkot-Ahmedabad", "North & West India", [[22.99, 72.38], [22.72, 71.63], [22.30, 70.80]]),
  corridor("sg-highway-ahmedabad", "Sarkhej-Gandhinagar Highway", "Ahmedabad-Gandhinagar", "North & West India", [[23.02, 72.50], [23.08, 72.53], [23.21, 72.64]]),
  corridor("mumbai-pune-expressway", "Mumbai-Pune Expressway", "Mumbai-Pune", "North & West India", [[18.83, 73.25], [18.76, 73.37], [18.65, 73.64]]),
  corridor("panvel-goa-nh66", "NH-66", "Panvel-Goa", "North & West India", [[18.99, 73.11], [17.58, 73.52], [15.49, 73.82]]),
  corridor("nh44-krishnagiri", "NH-44", "Krishnagiri toll plaza", "South India", [[12.84, 78.09], [12.52, 78.21], [12.26, 78.37]]),
  corridor("hyderabad-vijayawada-nh65", "NH-65", "Hyderabad-Vijayawada", "South India", [[17.26, 78.75], [17.14, 79.62], [16.68, 80.23]]),
  corridor("bengaluru-mysuru", "Bengaluru-Mysuru highway", "Bengaluru-Mysuru", "South India", [[12.73, 77.28], [12.72, 77.47], [12.64, 77.85]]),
  corridor("bengaluru-coorg", "Bengaluru-Coorg route", "Bengaluru-Coorg", "South India", [[12.73, 77.28], [12.42, 76.69], [12.42, 75.74]]),
  corridor("gudur-chennai-nh16", "NH-16", "Gudur-Chennai", "South India", [[13.99, 79.85], [13.58, 80.02], [13.08, 80.20]]),
  corridor("cochin-trivandrum-nh47", "NH-47", "Cochin-Trivandrum", "South India", [[9.93, 76.31], [9.50, 76.34], [8.89, 76.61]]),
  corridor("odisha-nh16", "NH-16", "Odisha corridor", "East & Central India", [[20.35, 85.95], [20.25, 85.81], [19.81, 85.84]]),
  corridor("kolkata-asansol-nh19", "NH-19", "Kolkata-Asansol", "East & Central India", [[22.75, 88.14], [23.23, 87.86], [23.68, 86.98]]),
  corridor("govindpur-nh19", "NH-19", "Govindpur Jharkhand", "East & Central India", [[23.77, 86.42], [23.82, 86.52], [23.90, 86.73]]),
  corridor("aurangabad-bihar-nh19", "NH-19", "Aurangabad Bihar", "East & Central India", [[24.76, 84.36], [24.89, 84.48], [25.06, 84.68]]),
  corridor("hyderabad-nagpur-nh44", "NH-44", "Hyderabad-Nagpur", "East & Central India", [[18.67, 78.10], [19.67, 78.53], [20.71, 79.00]]),
  corridor("guwahati-shillong-nh6", "NH-6", "Guwahati-Shillong", "North-East India", [[26.10, 91.84], [25.90, 91.88], [25.58, 91.88]]),
  corridor("assam-raha-nh27", "NH-27", "Guwahati-Kaziranga", "North-East India", [[26.23, 92.29], [26.25, 92.52], [26.58, 93.14]]),
];

function corridor(
  id: string,
  highwayName: string,
  routeContext: string,
  region: string,
  points: Array<[number, number]>,
): HighwaySearchCorridor {
  return {
    id,
    highwayName,
    routeContext,
    region,
    anchors: points.map(([latitude, longitude]) => ({ latitude, longitude, radiusMeters: 30_000 })),
    polyline: points.map(([latitude, longitude]) => ({ latitude, longitude })),
  };
}